name: CN EPG Fetcher

on:
  schedule:
    - cron: "0 */4 * * *"  # 每4小时执行一次
  workflow_dispatch:  # 手动触发

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch and save EPG data
      run: |
        import requests
        from xml.etree import ElementTree

        def fetch_data():
            iptv_url = "https://raw.githubusercontent.com/Yu0754/IPTV/refs/heads/main/iptv.txt"
            response = requests.get(iptv_url)
            
            if response.status_code != 200:
                print(f"Error fetching IPTV file: {response.status_code}")
                return

            lines = response.text.splitlines()
            url = ""
            user_agent = ""
            for i, line in enumerate(lines):
                if "# 中国电视" in line:
                    url = lines[i + 1].strip()
                elif "# USER_AGENT" in line:
                    user_agent = lines[i + 1].strip()
            
            if not url or not user_agent:
                print("Error: Couldn't find required parameters.")
                return

            headers = {'User-Agent': user_agent}
            response = requests.get(url, headers=headers)
            
            if response.status_code != 200:
                print(f"Error fetching URL: {response.status_code}")
                return

            x_tvg_url = ""
            for line in response.text.splitlines():
                if "x-tvg-url" in line:
                    x_tvg_url = line.split('=')[1].strip().strip('"')
                    break

            if not x_tvg_url:
                print("Error: Couldn't find x-tvg-url.")
                return

            response = requests.get(x_tvg_url, headers=headers)
            
            if response.status_code != 200:
                print(f"Error fetching x-tvg-url content: {response.status_code}")
                return

            with open('cnepg.xml', 'wb') as file:
                file.write(response.content)
            print("EPG data saved to cnepg.xml.")

        fetch_data()

    - name: Upload cnepg.xml to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cnepg.xml
        path: cnepg.xml
