name: CN Logo

on:
  schedule:
    - cron: '0 0 * * *'  # 每24小时运行一次
  workflow_dispatch:        # 手动触发

jobs:
  download-cn-logos:
    runs-on: ubuntu-22.04

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 从 url.txt 提取目标 URL
    - name: Extract URL from url.txt
      run: |
        echo "Fetching url.txt from GitHub..."
        URL_FILE=$(curl -s https://raw.githubusercontent.com/Yu0754/IPTV/refs/heads/main/url.txt)
        
        # 打印 url.txt 内容（仅供调试）
        echo "url.txt content:"
        echo "$URL_FILE"
        
        # 提取 "# 中国电视" 下面一行的 URL
        TARGET_URL=$(echo "$URL_FILE" | grep -A 1 "# 中国电视" | tail -n 1 | tr -d '\r')
        
        # 检查是否成功提取 URL
        echo "Extracted URL: $TARGET_URL"
        
        if [ -z "$TARGET_URL" ]; then
          echo "Target URL not found or is empty"
          exit 1
        fi

    # 使用模拟播放器读取目标 URL 的内容
    - name: Fetch content from target URL
      run: |
        # 使用模拟播放器的 User-Agent
        USER_AGENT="AptvPlayer/1.3.16"
        CONTENT=$(curl -sL -A "$USER_AGENT" "$TARGET_URL")
        
        # 打印读取的内容（仅供调试）
        echo "Fetched content from $TARGET_URL:"
        echo "$CONTENT"
        
        # 保存内容到临时文件
        echo "$CONTENT" > temp_content.txt

    # 创建 CN Logo 文件夹
    - name: Create CN Logo folder
      run: |
        mkdir -p "CN Logo"

    # 提取和下载 .png 文件到 CN Logo 文件夹
    - name: Extract and download .png URLs
      run: |
        grep -oE 'http[^ ]+\.png' temp_content.txt | while read -r URL; do
          echo "Downloading $URL"
          curl -s -O -J "$URL" --output-dir "CN Logo"
        done

    # 提交并推送 CN Logo 文件夹到仓库
    - name: Commit and push CN Logo folder
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add "CN Logo"
        git commit -m "Update CN Logo folder on $(date)"
        git push origin main || echo "No changes to push"
