name: Update CN Live

on:
  schedule:
    - cron: '0 */4 * * *'  # 每4小时运行一次
  workflow_dispatch:        # 手动触发

jobs:
  update-m3u:
    runs-on: ubuntu-22.04

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 下载并处理 M3U 文件
    - name: Download and process M3U file
      run: |
        # 下载指定 M3U 文件
        curl -sL https://raw.githubusercontent.com/suxuang/myIPTV/refs/heads/main/ipv6.m3u -o ipv6.m3u

        # 按需求处理文件
        awk '
        BEGIN { retain = 1; section = 1 }
        /^#EXTINF.*CCTV17/ { print $0; getline; print $0; section = 2; next }  # CCTV17 段结束
        section == 1 { print $0 }                                             # 保留第一段内容

        /^#卫视频道/ { section = 3 }                                          # 开始卫视频道段
        section == 3 { print $0 }
        /^#EXTINF.*广东珠江/ { print $0; getline; print $0; section = 4; next } # 广东珠江段结束

        END { if (section != 4) exit 1 }  # 确保流程正确，否则返回错误
        ' ipv6.m3u > cnlive.m3u

        # 确认结果
        echo "Processed CNLIVE.m3u:"
        cat cnlive.m3u

    # 提交并推送更改
    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add cnlive.m3u
        git commit -m "Update cnlive.m3u on $(date)" || echo "No changes to commit"
        git push origin main
