name: Update TV Live

on:
  schedule:
    - cron: '0 */4 * * *'  # 每4小时运行一次
  workflow_dispatch:  # 手动触发

jobs:
  update-m3u:
    runs-on: ubuntu-22.04  # 显式指定兼容的环境

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 下载并修改 m3u 文件
    - name: Download and process M3U file
      run: |
        # 创建目录
        mkdir -p m3u_files
        
        # 下载 ipv6.m3u 文件
        curl -sL https://raw.githubusercontent.com/suxuang/myIPTV/refs/heads/main/ipv6.m3u -o m3u_files/ipv6.m3u
        
        # 输出原始文件内容（用于调试）
        echo "Original ipv6.m3u content:"
        cat m3u_files/ipv6.m3u

        # 过滤文件：保留仅包含 "CCTV" 或 "卫视" 的行及其下一行，且仅限 IPv6 地址
        awk '
        BEGIN { retain = 0 }
        /^#EXTINF:/ {
            retain = ($0 ~ /CCTV/ || $0 ~ /卫视/)
            if (retain) info = $0
        }
        retain == 1 && /^[^#]/ {
            if ($0 ~ /^\[.*\]:/) {  # 检查是否为 IPv6 地址
                print info
                print $0
            }
            retain = 0
        }' m3u_files/ipv6.m3u > cnlive.m3u

        # 在文件最前面添加指定的行
        sed -i '1i #EXTM3U x-tvg-url="https://live.fanmingming.com/e.xml"' cnlive.m3u

        # 替换 fanmingming.cn 为 fanmingming.com
        sed -i 's/fanmingming.cn/fanmingming.com/g' cnlive.m3u

        # 输出处理后的文件内容（用于调试）
        echo "Processed cnlive.m3u content:"
        cat cnlive.m3u

    # 提交并推送更改
    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add cnlive.m3u
        git commit -m "Update cnlive.m3u on $(date)" || echo "No changes to commit"
        git push origin main
