name: Update CN Live

on:
  schedule:
    - cron: '0 */4 * * *'  # 每4小时运行一次
  workflow_dispatch:        # 手动触发

jobs:
  update-m3u:
    runs-on: ubuntu-22.04

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 下载并处理 M3U 文件
    - name: Download and process M3U file
      run: |
        # 下载指定 M3U 文件
        curl -sL https://raw.githubusercontent.com/suxuang/myIPTV/refs/heads/main/ipv6.m3u -o ipv6.m3u

        # 按需求处理文件
        awk '
        BEGIN { retain = 0 }
        /CCTV17/ { retain = 1 }  # 开始保留从包含 CCTV17 的行
        retain { print $0 }      # 保留内容
        /CCTV17/ { getline; print $0 } # 保留 CCTV17 下一行
        ' ipv6.m3u > temp1.m3u

        awk '
        BEGIN { retain = 0 }
        /#卫视频道/ { retain = 1 }  # 开始保留从 #卫视频道
        retain { print $0 }
        /广东珠江/ { print $0; getline; print $0; retain = 0 }  # 保留广东珠江及其下一行，结束保留
        ' temp1.m3u > temp2.m3u

        awk '
        BEGIN { retain = 0 }
        /#春晚/ { retain = 1 }  # 开始保留从 #春晚
        retain { print $0 }
        /#国际频道/ { retain = 0; next } # 结束保留之前的内容
        ' temp2.m3u > cnlive.m3u

        # 确认结果
        echo "Processed CNLIVE.m3u:"
        cat cnlive.m3u

    # 提交并推送更改
    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add cnlive.m3u
        git commit -m "Update cnlive.m3u on $(date)" || echo "No changes to commit"
        git push origin main
