name: CN Live

on:
  schedule:
    - cron: '0 */4 * * *'  # 每4小时运行一次
  workflow_dispatch:        # 手动触发

concurrency:
  group: update-m3u-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-m3u:
    runs-on: ubuntu-22.04

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 下载并保存 M3U 文件
      - name: Download and process M3U file
        run: |
          set -e

          # 定义 URL 文件路径
          IPTV_FILE="https://raw.githubusercontent.com/Yu0754/IPTV/main/iptv.txt"

          # 提取 M3U URL 和 User-Agent
          echo "Fetching iptv.txt..."
          IPTV_CONTENT=$(curl -sL "$IPTV_FILE" || { echo "Error: Failed to fetch iptv.txt"; exit 1; })
          
          M3U_URL=$(echo "$IPTV_CONTENT" | awk '/# 中国电视/{getline; print}' | tr -d '\r')
          USER_AGENT=$(echo "$IPTV_CONTENT" | awk '/# USER_AGENT/{getline; print}' | tr -d '\r')

          # 检查是否成功提取 URL 和 User-Agent
          if [ -z "$M3U_URL" ]; then
            echo "Error: Failed to extract M3U URL from iptv.txt" >&2
            exit 1
          fi
          if [ -z "$USER_AGENT" ]; then
            echo "Error: Failed to extract USER_AGENT from iptv.txt" >&2
            exit 1
          fi

          echo "Extracted M3U URL: $M3U_URL"
          echo "Extracted USER_AGENT: $USER_AGENT"

          # 下载 M3U 文件并保存为 cnlive.m3u
          echo "Downloading M3U file..."
          curl -sL -A "$USER_AGENT" "$M3U_URL" -o cnlive.m3u || { echo "Error: Failed to download M3U file"; exit 1; }

          if [ ! -s cnlive.m3u ]; then
            echo "Error: cnlive.m3u file is empty" >&2
            exit 1
          fi

          # 保留所需内容并删除其他内容
          echo "Filtering content..."
          awk '
          # 从开头到包含CCTV17的那一行以及下一行
          /^CCTV17/ {print; getline; print; exit}
          # 从含有#卫视频道到包含广东珠江的那一行以及下一行
          /#卫视频道/ {print; found=true}
          found && /广东珠江/ {print; exit}
          ' cnlive.m3u > cnlive_filtered.m3u || { echo "Error: Failed to filter cnlive.m3u"; exit 1; }

          mv cnlive_filtered.m3u cnlive.m3u

          # 替换 x-tvg-url
          echo "Replacing x-tvg-url with new URL..."
          sed -i 's|x-tvg-url="[^"]*"|x-tvg-url="https://raw.githubusercontent.com/Yu0754/IPTV/main/cnepg.xml"|g' cnlive.m3u

          # 替换 .png 文件的 URL
          echo "Updating .png file URLs..."
          sed -i 's|\(http[^ ]*/\)\([^/]*\.png\)|https://raw.githubusercontent.com/Yu0754/IPTV/main/CN Logo/\2|' cnlive.m3u

          # 确认处理结果
          echo "Processed cnlive.m3u (preview):"
          head -n 10 cnlive.m3u || { echo "Error: Failed to process cnlive.m3u"; exit 1; }

      # 提交并推送更改
      - name: Commit and push changes
        run: |
          set -e
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

          # 检查是否有未提交的更改，如果有，先提交
          git add . || echo "No changes to commit"

          # 提交更改
          git commit -m "Update cnlive.m3u on $(date)" || echo "No changes to commit"

          # 确保无冲突更新
          git pull --rebase origin main || { echo "Error: Git pull failed"; exit 1; }

          # 推送更改
          git push origin main || { echo "Error: Git push failed. Ensure no conflicts exist."; exit 1; }
