name: Update CN Live

on:
  schedule:
    - cron: '0 */4 * * *'  # 每4小时运行一次
  workflow_dispatch:        # 手动触发

jobs:
  update-m3u:
    runs-on: ubuntu-22.04

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 下载并处理 M3U 文件
    - name: Download and process M3U file
      run: |
        # 下载指定 M3U 文件
        curl -sL https://raw.githubusercontent.com/suxuang/myIPTV/refs/heads/main/ipv6.m3u -o ipv6.m3u

        # 处理文件
        awk '
        BEGIN { retain = 0; output = 0 }
        # 保留从文件开头到 CCTV17 及其下一行
        NR == 1 { retain = 1; output = 1 }
        /CCTV17/ && retain == 1 { print; getline; print; retain = 0 }
        output == 1 && retain == 1 { print }

        # 保留从 #卫视频道 到 广东珠江 及其下一行
        /#卫视频道/ { retain = 1; output = 2 }
        /广东珠江/ && output == 2 && retain == 1 { print; getline; print; retain = 0 }
        output == 2 && retain == 1 { print }

        # 保留从 #春晚 到 #国际频道 的上一行
        /#春晚/ { retain = 1; output = 3 }
        /#国际频道/ && output == 3 { retain = 0 }
        output == 3 && retain == 1 { print }
        ' ipv6.m3u > cnlive.m3u

        # 确认结果
        echo "Processed CNLIVE.m3u:"
        cat cnlive.m3u

    # 提交并推送更改
    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add cnlive.m3u
        git commit -m "Update cnlive.m3u on $(date)" || echo "No changes to commit"
        git push origin main
