name: CN Live

on:
  schedule:
    - cron: '0 */4 * * *'  # 每4小时运行一次
  workflow_dispatch:        # 手动触发

jobs:
  update-m3u:
    runs-on: ubuntu-22.04

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 从 url.txt 提取 # 中国电视 下的 URL
    - name: Extract URL from url.txt
      run: |
        echo "Fetching url.txt from GitHub..."
        URL_FILE=$(curl -s https://raw.githubusercontent.com/Yu0754/IPTV/refs/heads/main/url.txt)
        
        echo "url.txt content:"
        echo "$URL_FILE"
        
        # 提取 # 中国电视 下的一行 URL
        TARGET_URL=$(echo "$URL_FILE" | grep -A 1 "# 中国电视" | tail -n 1 | tr -d '\r')
        echo "Extracted URL: $TARGET_URL"

        # 验证提取的 URL 是否有效
        if [ -z "$TARGET_URL" ]; then
          echo "Target URL not found or is empty"
          exit 1
        fi
        if [[ ! "$TARGET_URL" =~ ^https?:// ]]; then
          echo "Extracted URL is not a valid HTTP(S) URL: $TARGET_URL"
          exit 1
        fi

        # 保存提取的 URL 供后续步骤使用
        echo "TARGET_URL=$TARGET_URL" >> $GITHUB_ENV

    # 使用模拟播放器的 User-Agent 读取目标内容
    - name: Fetch content from target URL
      run: |
        USER_AGENT="AptvPlayer/1.3.16"
        echo "Fetching content from $TARGET_URL..."
        curl -sL -A "$USER_AGENT" "$TARGET_URL" -o temp_content.txt
        
        echo "Fetched content:"
        cat temp_content.txt

    # 下载并处理 M3U 文件
    - name: Download and process M3U file
      run: |
        # 下载指定 M3U 文件
        curl -sL https://raw.githubusercontent.com/suxuang/myIPTV/refs/heads/main/ipv6.m3u -o ipv6.m3u

        # 按需求处理文件
        awk '
        BEGIN { 
            section = 1; 
            found_cctv17 = 0; 
            found_guangdong = 0; 
        }
        
        # 第一段：从文件开始到 CCTV17 及其下面一行
        section == 1 {
            print $0;
            if (/^#EXTINF.*CCTV17/) { 
                found_cctv17 = 1; 
            } 
            if (found_cctv17 && /^http/) { 
                section = 2; 
                next; 
            } 
        }

        # 第二段：从 #卫视频道 到 广东珠江 及其下面一行
        /^#卫视频道/ { section = 3 }
        section == 3 {
            print $0;
            if (/^#EXTINF.*广东珠江/) {
                found_guangdong = 1;
            }
            if (found_guangdong && /^http/) { 
                exit; 
            }
        }
        ' ipv6.m3u > cnlive.m3u

        # 确认结果
        echo "Processed CNLIVE.m3u:"
        cat cnlive.m3u

    # 提交并推送更改
    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add cnlive.m3u
        git commit -m "Update cnlive.m3u on $(date)" || echo "No changes to commit"
        git push origin main
