name: CN Logo

on:
  schedule:
    - cron: '0 0 * * *'  # 每24小时运行一次
  workflow_dispatch:        # 手动触发

jobs:
  download-cn-logos:
    runs-on: ubuntu-22.04

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 下载 cnlive.m3u 文件
    - name: Download cnlive.m3u
      run: |
        curl -sL https://raw.githubusercontent.com/Yu0754/IPTV/refs/heads/main/cnlive.m3u -o cnlive.m3u

    # 创建 CN Logo 文件夹
    - name: Create CN Logo folder
      run: |
        mkdir -p "CN Logo"

    # 提取和下载 .png 文件到 CN Logo 文件夹
    - name: Extract and download .png URLs
      run: |
        grep -oE 'http[^ ]+\.png' cnlive.m3u | while read -r URL; do
          echo "Downloading $URL"
          curl -s -O -J "$URL" --output-dir "CN Logo"
        done

    # 提交并推送 CN Logo 文件夹到仓库
    - name: Commit and push CN Logo folder
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add "CN Logo"
        git commit -m "Update CN Logo folder on $(date)"
        git push origin main || echo "No changes to push"
