- name: Process M3U file
  run: |
    # 下载文件
    curl -sL https://raw.githubusercontent.com/suxuang/myIPTV/refs/heads/main/ipv6.m3u -o ipv6.m3u

    # 检查下载是否成功
    if [ ! -s ipv6.m3u ]; then
      echo "Failed to download M3U file or file is empty!"
      exit 1
    fi

    # 输出文件内容
    echo "Downloaded M3U file content:"
    head -n 20 ipv6.m3u

    # 提取包含 CCTV 开头的频道信息
    grep -E "(#EXTINF.*CCTV|http.*CCTV)" ipv6.m3u > cnlive.m3u

    # 检查提取结果
    if [ ! -s cnlive.m3u ]; then
      echo "Generated file is empty. Please check matching logic!"
      exit 1
    fi

    # 输出生成文件
    echo "Processed M3U file content:"
    cat cnlive.m3u
