name: Test CCTV Extract

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y ffmpeg
        pip install requests

    - name: Run extractor
      run: python extract.py

    - name: Commit results if changed
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add real_urls.txt
        CHANGED=$(git diff --cached --quiet; echo $?)
        if [ "$CHANGED" -ne 0 ]; then
          git commit -m "Test extract CCTV1/2"
          git push
        else
          echo "No changes to commit."
        fi
