name: Download M3U Playlist

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download-m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Download M3U and save to file
        run: |
          import requests

          # M3U URL
          url = 'https://www.stream-link.org/playlist.m3u?token=71a2af8c-8fec-4901-8e31-919c53a57c58&hmac=a202f253638c212fa272ecce2b0c7b49'

          # Send GET request to fetch M3U content
          response = requests.get(url)

          if response.status_code == 200:
              # Save content to a file
              with open('playlist.m3u', 'w') as f:
                  f.write(response.text)
              print("M3U file saved as 'playlist.m3u'")
          else:
              print(f"Request failed with status code: {response.status_code}")

      - name: Upload M3U file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: playlist-m3u
          path: playlist.m3u
