name: FG EPG

on:
  schedule:
    - cron: '0 */4 * * *' # 每4小时运行一次
  workflow_dispatch: # 手动触发

concurrency:
  group: update-epg-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-epg:
    runs-on: ubuntu-22.04

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 获取 iptv.txt 文件的内容并下载 EPG 数据
      - name: Download and process EPG data
        run: |
          set -e

          # 下载 iptv.txt 文件
          IPTV_FILE=$(curl -s https://raw.githubusercontent.com/Yu0754/IPTV/main/iptv.txt)
          [ -z "$IPTV_FILE" ] && exit 1

          # 提取 M3U URL
          M3U_URL=$(echo "$IPTV_FILE" | grep -A 1 "# 全球电视" | tail -n 1 | tr -d '\r')
          [ -z "$M3U_URL" ] && exit 1

          # 提取 User-Agent
          USER_AGENT=$(echo "$IPTV_FILE" | grep -A 1 "# USER_AGENT" | tail -n 1 | tr -d '\r')
          [ -z "$USER_AGENT" ] && exit 1

          # 下载 M3U 内容
          EPG_FILE=$(curl -sL -A "$USER_AGENT" "$M3U_URL")
          [ -z "$EPG_FILE" ] && exit 1

          # 提取 x-tvg-url 的 URL
          X_TVG_URL=$(echo "$EPG_FILE" | grep -i "x-tvg-url" | cut -d '"' -f 2)
          [ -z "$X_TVG_URL" ] && exit 1

          # 下载 EPG 数据
          curl -sL -A "$USER_AGENT" "$X_TVG_URL" -o fgepg.xml
          [ ! -s fgepg.xml ] && exit 1

      # 提交并推送更改
      - name: Commit and push changes
        run: |
          set -e
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

          git pull --rebase origin main
          git add fgepg.xml
          git commit -m "Update fgepg.xml on $(date)" || true
          git push origin main || true
