name: FG Logo

on:
  workflow_dispatch:        # 手动触发

jobs:
  download-logos:
    runs-on: ubuntu-22.04

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 创建存储 Logo 的文件夹
    - name: Create FG Logo folder
      run: mkdir -p "FG_Logo"

    # 提取和下载 .png 文件
    - name: Extract and download .png URLs
      run: |
        # 定义 M3U 文件路径
        M3U_FILE="fglive.m3u"

        # 确保文件存在
        if [ ! -f "$M3U_FILE" ]; then
          echo "File $M3U_FILE does not exist. Please ensure the fglive.m3u file is generated first."
          exit 1
        fi

        # 读取包含 .png 的 URL，并逐个下载
        grep -oE 'http[^ ]+\.png' "$M3U_FILE" | while read -r URL; do
          echo "Downloading $URL"
          curl -s -O -J "$URL" --output-dir "FG_Logo"
        done

    # 列出下载的文件以确认内容
    - name: List downloaded files
      run: ls -l "FG_Logo"

    # 保存 FG Logo 文件夹为 Artifact
    - name: Upload FG Logo as artifact
      uses: actions/upload-artifact@v3
      with:
        name: FG_Logo
        path: FG_Logo/
