name: FG Logo

on:
  schedule:
    - cron: '0 0 * * *'  # 每24小时运行一次
  workflow_dispatch:        # 手动触发

jobs:
  download-logos:
    runs-on: ubuntu-22.04

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 下载 fglive.m3u 文件
    - name: Download fglive.m3u
      run: |
        curl -sL https://raw.githubusercontent.com/Yu0754/IPTV/refs/heads/main/fglive.m3u -o fglive.m3u

    # 创建 FG Logo 文件夹
    - name: Create FG Logo folder
      run: |
        mkdir -p "FG Logo"

    # 提取和下载 .png 文件到 FG Logo 文件夹
    - name: Extract and download .png URLs
      run: |
        grep -oE 'http[^ ]+\.png' fglive.m3u | while read -r URL; do
          echo "Downloading $URL"
          curl -s -O -J "$URL" --output-dir "FG Logo"
        done

    # 提交并推送 FG Logo 文件夹到仓库
    - name: Commit and push FG Logo folder
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add "FG Logo"
        git commit -m "Update FG Logo folder on $(date)"
        git push origin main || echo "No changes to push"
