name: FG Live

on:
  schedule:
    - cron: '0 */4 * * *'  # 每4小时运行一次
  workflow_dispatch:        # 手动触发

jobs:
  update-m3u:
    runs-on: ubuntu-22.04

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 下载并保存 M3U 文件
    - name: Download and save M3U file
      run: |
        # 定义URL文件的路径
        URL_FILE="https://raw.githubusercontent.com/Yu0754/IPTV/refs/heads/main/url.txt"

        # 从URL文件中提取包含 `# 全球电视` 那一行下面的URL
        M3U_URL=$(curl -sL "$URL_FILE" | awk '/# 全球电视/{getline; print}')

        # 检查是否成功提取URL
        if [ -z "$M3U_URL" ]; then
          echo "Error: Failed to extract M3U URL from url.txt" >&2
          exit 1
        fi

        echo "Extracted M3U URL: $M3U_URL"

        # 自定义 User-Agent 模拟播放器
        USER_AGENT="AptvPlayer/1.3.16"

        # 使用提取的URL下载文件并保存为 fglive.m3u
        curl -sL -A "$USER_AGENT" "$M3U_URL" -o fglive.m3u

        # 提取包含 x-tvg-url 的行并提取 URL
        TVG_URL=$(grep -oP 'x-tvg-url="\K[^"]+' fglive.m3u)

        # 替换原有的 x-tvg-url 行中的 URL 为新的 URL
        sed -i \
          -e 's|x-tvg-url="[^"]*"|x-tvg-url="https://raw.githubusercontent.com/Yu0754/IPTV/refs/heads/main/fgepg.xml"|g' \
          -e '/免费使用规则/{N;d;}' \
          fglive.m3u

        # 替换 .png 文件的 URL
        sed -i 's|\(http[^ ]*/\)\([^/]*\.png\)|https://raw.githubusercontent.com/Yu0754/IPTV/refs/heads/main/FG Logo/\2|' fglive.m3u

        # 确认结果
        echo "Processed fglive.m3u:"
        cat fglive.m3u

    # 提交并推送更改
    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add fglive.m3u
        git commit -m "Update fglive.m3u on $(date)" || echo "No changes to commit"
        git push origin main
