name: FG Live2

on:
  schedule:
    - cron: '0 */4 * * *'  # 每4小时运行一次
  workflow_dispatch:        # 手动触发

jobs:
  update-m3u:
    runs-on: ubuntu-22.04

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 下载 fglive.m3u 文件并处理
    - name: Process M3U file
      run: |
        # 定义变量
        SOURCE_URL="https://raw.githubusercontent.com/Yu0754/IPTV/refs/heads/main/fglive.m3u"
        TEMP_FILE="fglive_temp.m3u"
        OUTPUT_FILE="fglive2.m3u"
        USER_AGENT="AptvPlayer/1.3.16"

        # 下载文件
        curl -sL "$SOURCE_URL" -o "$TEMP_FILE"

        # 初始化输出文件
        echo "#EXTM3U" > "$OUTPUT_FILE"

        # 遍历文件并处理包含 sc2025.stream-link.org 的 URL
        while IFS= read -r line; do
          if echo "$line" | grep -q "sc2025.stream-link.org"; then
            echo "Processing: $line"

            # 提取真实播放地址
            REAL_URL=$(curl -sL -A "$USER_AGENT" "$line" | grep -oP 'https?://[^\s"]+')

            # 如果成功提取真实地址，替换原始行
            if [ -n "$REAL_URL" ]; then
              echo "Replacing URL: $REAL_URL"
              echo "$REAL_URL" >> "$OUTPUT_FILE"
            else
              echo "Failed to extract URL, keeping original: $line"
              echo "$line" >> "$OUTPUT_FILE"
            fi

            # 延迟 2 秒
            sleep 2
          else
            # 非 URL 行直接复制
            echo "$line" >> "$OUTPUT_FILE"
          fi
        done < "$TEMP_FILE"

    # 提交并推送更改
    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add fglive2.m3u
        git commit -m "Update fglive2.m3u on $(date)" || echo "No changes to commit"
        git push origin main
