name: FG Live

on:
  schedule:
    - cron: '0 */4 * * *'  # 每4小时运行一次
  workflow_dispatch:        # 手动触发

jobs:
  update-m3u:
    runs-on: ubuntu-22.04

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 下载并保存 M3U 文件
    - name: Download and save M3U file
      run: |
        # 定义 M3U 文件的 URL
        M3U_URL="https://www.stream-link.org/playlist.m3u?token=71a2af8c-8fec-4901-8e31-919c53a57c58&hmac=a202f253638c212fa272ecce2b0c7b49"

        # 自定义 User-Agent 模拟播放器
        USER_AGENT="AptvPlayer/1.3.16"

        # 使用 curl 下载文件并保存为 fglive.m3u
        curl -sL -A "$USER_AGENT" "$M3U_URL" -o fglive.m3u

        # 提取包含 x-tvg-url 的行并提取 URL
        TVG_URL=$(grep -oP 'x-tvg-url="\K[^"]+' fglive.m3u)

        # 在文件开头添加 # 注释行，插入提取到的 URL
        sed -i "1i # $TVG_URL" fglive.m3u

        # 替换原有的 x-tvg-url 行中的 URL 为新的 URL
        sed -i \
          -e "s|x-tvg-url=\"$TVG_URL\"|x-tvg-url=\"https://raw.githubusercontent.com/Yu0754/IPTV/refs/heads/main/fgepg.xml\"|g" \
          -e 's|https://content.stream-link.org/images|https://raw.githubusercontent.com/Yu0754/IPTV/refs/heads/main/FG Logo|g' \
          -e '/免费使用规则/{N;d;}' \
          fglive.m3u

        # 确认结果
        echo "Processed fglive.m3u:"
        cat fglive.m3u

    # 提交并推送更改
    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add fglive.m3u
        git commit -m "Update fglive.m3u on $(date)" || echo "No changes to commit"
        git push origin main
