name: Update TVLive M3U

on:
  schedule:
    - cron: '0 */4 * * *'  # 每4小时运行一次
  workflow_dispatch:  # 手动触发

jobs:
  update-m3u:
    runs-on: ubuntu-22.04  # 显式指定兼容的环境

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 下载并修改 m3u 文件
    - name: Download and process M3U file
      run: |
        # 创建目录
        mkdir -p m3u_files
        
        # 下载 ipv6.m3u 文件
        curl -sL -o
