name: Fetch IPTV via Puppeteer

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # 每 6 小时自动运行一次

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install puppeteer

      - name: Run Puppeteer script
        run: node fetch.js

      - name: Commit and push iptv.m3u
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add iptv.m3u
          git commit -m "Update IPTV playlist via Puppeteer"
          git push
