name: Fetch IPTV

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次，可自行调整

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download iptv.m3u from Cloudflare Tunnel
        run: curl -s -f -u yu0754:lh100172 https://packages-wait-ranks-polyphonic.trycloudflare.com/iptv.m3u -o iptv.m3u

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add iptv.m3u
          git commit -m "Update iptv.m3u"
          git push
