name: Test

on:
  workflow_dispatch:  # 手动触发

jobs:
  test-url:
    runs-on: ubuntu-22.04

    steps:
    # 模拟播放器访问 URL 并保存真实播放地址
    - name: Fetch real playback URL
      run: |
        # 定义测试地址
        TEST_URL="https://sc2025.stream-link.org/playlist/f7dec06f0b24.php?id=sgp0269kdbd&token=71a2af8c-8fec-4901-8e31-919c53a57c58&hmac=a202f253638c212fa272ecce2b0c7b49"
        USER_AGENT="AptvPlayer/1.3.16"
        OUTPUT_FILE="test.m3u"

        # 模拟播放器访问并获取真实 URL
        REAL_URL=$(curl -sL -A "$USER_AGENT" "$TEST_URL" | grep -oP 'https?://[^\s"]+')

        # 验证提取的真实地址
        if [ -n "$REAL_URL" ]; then
          echo "#EXTM3U" > "$OUTPUT_FILE"
          echo "#EXTINF:-1,Test Stream" >> "$OUTPUT_FILE"
          echo "$REAL_URL" >> "$OUTPUT_FILE"
          echo "Real URL extracted and saved to $OUTPUT_FILE"
        else
          echo "Failed to extract real URL from: $TEST_URL"
          exit 1
        fi

    # 输出结果文件内容
    - name: Show test.m3u content
      run: |
        echo "Generated test.m3u file:"
        cat test.m3u
