name: Update TVLive M3U

on:
  schedule:
    - cron: '0 */4 * * *'  # 每4小时运行一次
  workflow_dispatch:  # 手动触发

jobs:
  update-m3u:
    runs-on: ubuntu-22.04  # 显式指定兼容的环境

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 下载两个 m3u 文件并直接修改 live.m3u
    - name: Download and edit M3U files
      run: |
        mkdir -p m3u_files
        curl -sL -o m3u_files/ipv6.m3u https://live.fanmingming.com/tv/m3u/ipv6.m3u
        curl -sL -o m3u_files/live.m3u http://aktv.top/live.m3u
        # 替换 live.m3u 文件中的 group-title="AKTV"
        sed -i 's/group-title="AKTV"/group-title="港台频道"/g' m3u_files/live.m3u
        ls -l m3u_files  # 检查文件是否下载并修改成功
        cat m3u_files/live.m3u | grep 'group-title="港台频道"' || echo "No matching lines replaced!"

    # 合并文件并去重
    - name: Merge and deduplicate M3U files
      run: |
        cat m3u_files/ipv6.m3u m3u_files/live.m3u | awk '!seen[$0]++' > tvlive.m3u
        ls -l  # 检查合并后的文件是否生成
        cat tvlive.m3u || echo "Merged M3U file not found or empty!"

    # 提交并推送更改
    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git reset --hard  # 清理所有未提交的更改
        git pull origin main --rebase  # 拉取远程最新代码，避免冲突
        git add tvlive.m3u
        git commit -m "Update tvlive.m3u on $(date)" || echo "No changes to commit"
        git push origin main
